import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    /* Superset/tri-set group colors: border, chip, card tint (so dynamic classes are not purged) */
    "border-l-blue-500",
    "border-l-emerald-500",
    "border-l-amber-500",
    "border-l-violet-500",
    "border-l-rose-500",
    "border-l-teal-500",
    "border-l-orange-500",
    "border-l-fuchsia-500",
    "bg-blue-50/50",
    "dark:bg-blue-950/25",
    "bg-blue-100",
    "text-blue-800",
    "dark:bg-blue-950/60",
    "dark:text-blue-200",
    "border-blue-300",
    "dark:border-blue-700",
    "bg-emerald-50/50",
    "dark:bg-emerald-950/25",
    "bg-emerald-100",
    "text-emerald-800",
    "dark:bg-emerald-950/60",
    "dark:text-emerald-200",
    "border-emerald-300",
    "dark:border-emerald-700",
    "bg-amber-50/50",
    "dark:bg-amber-950/25",
    "bg-amber-100",
    "text-amber-800",
    "dark:bg-amber-950/60",
    "dark:text-amber-200",
    "border-amber-300",
    "dark:border-amber-700",
    "bg-violet-50/50",
    "dark:bg-violet-950/25",
    "bg-violet-100",
    "text-violet-800",
    "dark:bg-violet-950/60",
    "dark:text-violet-200",
    "border-violet-300",
    "dark:border-violet-700",
    "bg-rose-50/50",
    "dark:bg-rose-950/25",
    "bg-rose-100",
    "text-rose-800",
    "dark:bg-rose-950/60",
    "dark:text-rose-200",
    "border-rose-300",
    "dark:border-rose-700",
    "bg-teal-50/50",
    "dark:bg-teal-950/25",
    "bg-teal-100",
    "text-teal-800",
    "dark:bg-teal-950/60",
    "dark:text-teal-200",
    "border-teal-300",
    "dark:border-teal-700",
    "bg-orange-50/50",
    "dark:bg-orange-950/25",
    "bg-orange-100",
    "text-orange-800",
    "dark:bg-orange-950/60",
    "dark:text-orange-200",
    "border-orange-300",
    "dark:border-orange-700",
    "bg-fuchsia-50/50",
    "dark:bg-fuchsia-950/25",
    "bg-fuchsia-100",
    "text-fuchsia-800",
    "dark:bg-fuchsia-950/60",
    "dark:text-fuchsia-200",
    "border-fuchsia-300",
    "dark:border-fuchsia-700",
  ],
  theme: {
    extend: {
      colors: {
        primary: {
          DEFAULT: "var(--primary)",
          hover: "var(--primary-hover)",
          active: "var(--primary-active)",
          disabled: "var(--primary-disabled)",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          hover: "var(--secondary-hover)",
        },
        surface: "var(--surface)",
        background: "var(--background)",
        border: "var(--border)",
        muted: "var(--muted-text)",
        success: {
          DEFAULT: "var(--success)",
          hover: "var(--success-hover)",
        },
        error: {
          DEFAULT: "var(--error)",
          hover: "var(--error-hover)",
        },
        /* Chart palette for data viz */
        chart: {
          1: "var(--chart-1)",
          2: "var(--chart-2)",
          3: "var(--chart-3)",
          4: "var(--chart-4)",
          5: "var(--chart-5)",
          6: "var(--chart-6)",
        },
      },
      backgroundColor: {
        surface: "var(--surface)",
        background: "var(--background)",
      },
      textColor: {
        DEFAULT: "var(--text)",
        muted: "var(--muted-text)",
      },
      borderColor: {
        DEFAULT: "var(--border)",
      },
      ringColor: {
        primary: "var(--primary)",
      },
      boxShadow: {
        "focus-primary": "var(--focus-ring)",
      },
    },
  },
  plugins: [],
};
export default config;
